on: workflow_call

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: test
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        id: get-approver
        with:
          script: |
            // Get the approvals for this run
            const approvals = await github.request('GET /repos/{owner}/{repo}/actions/runs/{run_id}/approvals', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.runId
            })
            return approvals.data[0].user.login;
      # Runs a set of commands using the runners shell
      - name: Print Test
        run: |
          echo github.actor.. ${{ github.actor }}
          echo inputs.reason.. ${{ inputs.reason }}
          echo inputs.environment.. ${{ inputs.environment }}
          echo "${{ github.actor }} requested JIT for <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ inputs.reason }}>\nApproved By ${{steps.get-approver.outputs.result}}"
