# This is a basic workflow to help you get started with Actions

name: Test1

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      environment:
        type: string
        description: Select the environment
        default: "Prod"
      reason:
        description: Reason for Request (ICM or Description)
        type: string
        required: true


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Print Test
        run: |
          echo github.actor.. ${{ github.actor }}
          echo inputs.reason.. ${{ inputs.reason }}
          echo inputs.environment.. ${{ inputs.environment }}
          
  exec:
    uses: ./.github/workflows/test2.yml
